version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: sudo python setup.py install
          name: Install
      - run:
          command: ls
          name: Navigate to test files folder 
      - run:
          command: matrix
          name: Run utility

workflows:
  main:
    jobs:
      - build-and-test
